server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: zuul-service
  session:
    store-type: mongodb
zuul:
  routes:
    api-service-routing:
      path: /api/**
      serviceId: api-service
    webclient-service-routing:
      path: /**
      serviceId: webclient-service
  ignored-patterns:
    - /login**
    - /logout**